"""Tests for the SQL migration script generator."""

from app.diff.migration import generate_alter_scripts


def _diff(tables_added=None, tables_removed=None, fields_added=None,
          fields_removed=None, fields_modified=None, indexes_added=None,
          indexes_removed=None, relations_added=None, relations_removed=None,
          breaking_details=None):
    return {
        "tables_added": tables_added or [],
        "tables_removed": tables_removed or [],
        "tables_renamed": [],
        "fields_added": fields_added or [],
        "fields_removed": fields_removed or [],
        "fields_modified": fields_modified or [],
        "fields_renamed": [],
        "indexes_added": indexes_added or [],
        "indexes_removed": indexes_removed or [],
        "relations_added": relations_added or [],
        "relations_removed": relations_removed or [],
        "breaking_changes": bool(breaking_details),
        "breaking_details": breaking_details or [],
    }


class TestNoChanges:
    def test_empty_diff(self):
        sql = generate_alter_scripts(_diff())
        assert "No schema changes detected" in sql

    def test_comment_header(self):
        sql = generate_alter_scripts(_diff(fields_added=[{"table": "t", "field": "x", "definition": {"name": "x", "type": "int"}}]))
        assert "Migration generated by AI SQL Agent" in sql


class TestTableChanges:
    def test_create_table(self):
        diff = _diff(tables_added=[{
            "name": "coupons",
            "columns": [
                {"name": "id", "type": "int", "nullable": False, "primary_key": True},
                {"name": "code", "type": "varchar", "length": 50, "nullable": True},
            ],
            "indexes": [],
            "foreign_keys": [],
        }])
        sql = generate_alter_scripts(diff)
        assert "CREATE TABLE coupons" in sql
        assert "id int NOT NULL" in sql
        assert "code varchar(50)" in sql
        assert "PRIMARY KEY" in sql

    def test_drop_table(self):
        diff = _diff(tables_removed=[{"name": "old_table"}])
        sql = generate_alter_scripts(diff)
        assert "DROP TABLE IF EXISTS old_table" in sql


class TestFieldChanges:
    def test_add_field(self):
        diff = _diff(fields_added=[{
            "table": "orders",
            "field": "coupon_id",
            "definition": {"name": "coupon_id", "type": "int", "nullable": True},
        }])
        sql = generate_alter_scripts(diff)
        assert "ALTER TABLE orders ADD COLUMN coupon_id int" in sql

    def test_drop_field(self):
        diff = _diff(fields_removed=[{"table": "orders", "field": "old_col"}])
        sql = generate_alter_scripts(diff)
        assert "ALTER TABLE orders DROP COLUMN old_col" in sql

    def test_modify_field_mysql(self):
        diff = _diff(fields_modified=[{
            "table": "users",
            "field": "name",
            "before": {"type": "varchar", "length": 100, "nullable": True, "default": None},
            "after": {"type": "varchar", "length": 255, "nullable": True, "default": None},
        }])
        sql = generate_alter_scripts(diff, "mysql")
        assert "MODIFY COLUMN name varchar(255) NULL" in sql

    def test_modify_field_postgresql(self):
        diff = _diff(fields_modified=[{
            "table": "users",
            "field": "name",
            "before": {"type": "varchar", "length": 100, "nullable": True, "default": None},
            "after": {"type": "varchar", "length": 255, "nullable": True, "default": None},
        }])
        sql = generate_alter_scripts(diff, "postgresql")
        assert "ALTER COLUMN name TYPE varchar(255)" in sql


class TestIndexChanges:
    def test_create_index(self):
        diff = _diff(indexes_added=[{
            "table": "users",
            "index": {"name": "idx_name", "unique": False, "columns": ["name"]},
        }])
        sql = generate_alter_scripts(diff)
        assert "CREATE INDEX idx_name ON users" in sql

    def test_create_unique_index(self):
        diff = _diff(indexes_added=[{
            "table": "users",
            "index": {"name": "idx_email", "unique": True, "columns": ["email"]},
        }])
        sql = generate_alter_scripts(diff)
        assert "CREATE UNIQUE INDEX idx_email ON users(email)" in sql

    def test_drop_index_mysql(self):
        diff = _diff(indexes_removed=[{"table": "orders", "index": {"name": "idx_old"}}])
        sql = generate_alter_scripts(diff, "mysql")
        assert "DROP INDEX idx_old ON orders" in sql

    def test_drop_index_postgresql(self):
        diff = _diff(indexes_removed=[{"table": "orders", "index": {"name": "idx_old"}}])
        sql = generate_alter_scripts(diff, "postgresql")
        assert "DROP INDEX IF EXISTS idx_old" in sql


class TestRelationChanges:
    def test_add_foreign_key(self):
        diff = _diff(relations_added=[{
            "table": "orders",
            "relation": {"columns": ["user_id"], "ref_table": "users", "ref_columns": ["id"]},
        }])
        sql = generate_alter_scripts(diff)
        assert "ALTER TABLE orders ADD FOREIGN KEY (user_id) REFERENCES users(id)" in sql

    def test_remove_foreign_key_with_constraint_name(self):
        diff = _diff(relations_removed=[{
            "table": "orders",
            "relation": {"columns": ["user_id"], "ref_table": "users", "ref_columns": ["id"], "constraint_name": "fk_orders_user"},
        }])
        sql = generate_alter_scripts(diff, "mysql")
        assert "DROP FOREIGN KEY fk_orders_user" in sql

    def test_remove_foreign_key_postgresql(self):
        diff = _diff(relations_removed=[{
            "table": "orders",
            "relation": {"columns": ["user_id"], "ref_table": "users", "ref_columns": ["id"], "constraint_name": "fk_orders_user"},
        }])
        sql = generate_alter_scripts(diff, "postgresql")
        assert "DROP CONSTRAINT IF EXISTS fk_orders_user" in sql


class TestBreakingMarkers:
    def test_breaking_changes_marked(self):
        diff = _diff(
            tables_removed=[{"name": "obsolete"}],
            breaking_details=["table 'obsolete' removed"],
        )
        sql = generate_alter_scripts(diff)
        assert "destructive changes" in sql
        assert "WARNING: table 'obsolete' removed" in sql

    def test_non_breaking_no_marker(self):
        diff = _diff(fields_added=[{"table": "t", "field": "x", "definition": {"name": "x", "type": "int"}}])
        sql = generate_alter_scripts(diff)
        assert "destructive changes" not in sql


class TestDialectSpecific:
    def test_mysql_modify_column_uses_modify(self):
        diff = _diff(fields_modified=[{
            "table": "t",
            "field": "c",
            "before": {"type": "int", "nullable": False},
            "after": {"type": "bigint", "nullable": False},
        }])
        sql = generate_alter_scripts(diff, "mysql")
        assert "MODIFY COLUMN" in sql

    def test_postgresql_alter_column_uses_type(self):
        diff = _diff(fields_modified=[{
            "table": "t",
            "field": "c",
            "before": {"type": "int", "nullable": False},
            "after": {"type": "bigint", "nullable": False},
        }])
        sql = generate_alter_scripts(diff, "postgresql")
        assert "ALTER COLUMN c TYPE bigint" in sql

    def test_dialect_defaults_to_mysql(self):
        diff = _diff(fields_modified=[{
            "table": "t",
            "field": "c",
            "before": {"type": "int", "nullable": False},
            "after": {"type": "bigint", "nullable": False},
        }])
        sql = generate_alter_scripts(diff)
        assert "MODIFY COLUMN" in sql
